class AppStrings {
  AppStrings._();

  static const appName = 'FincaAPP';
  static const welcome = 'Welcome';
  static const enterEmail = "Enter your email";
  static const loginHere = 'Log in here';
  static const String login = 'Login';
  static const String dntHaveAccount = 'You do not have an account? Sign up';
  static const String theContinue = 'The continue with';
  static const didForgetPassword = 'Did you forget your password?';
  static const agreement =
      "By registering I agree with the terms and conditions and privacy policy of TediTerritorio";
  static const signup = "SignUp";
  static const haveAccountSignup = 'Do you have an account? Login';
  static const newFarm = "New Farm";
  static const addYourProperties = "Add your properties here";
  static const share = "Share";
  static const delete = "Delete";
  static const stepOne = "Step 1 of 4";
  static const stepTwo = "Step 2 of 4";
  static const stepThree = "Step 3 of 4";
  static const stepFour = "Step 4 of 4";
  static const stepOneDescription = "Select the location of the farm:";
  static const findLocation = "Find Location";
  static const undo = "Undo";
  static const cancel = "Cancel";
  static const closeForm = "Close Form";
  static const newPropertySave = "New property saved!";
  static const name = "*Name";
  static const size = "*Size";
  static const soilType = "*Soil Type";
  static const continueText = 'Continue';
  static const addTheCrops = '*Add the crops';
  static const addCrops = 'Add crop';
  static const newCrop = 'New Crop';
  static const cropName = '*Crop Name:';
  static const varieties = '*Varieties:';
  static const scientificName = '*Scientific Name:';
  static const seedTime = 'Seed Time:';
  static const sowingStatus = 'Sowing Status:';
  static const searchScientificName = "Search Scientific Name";
  static const sowingText = "Sowing";
  static const maintenance = "maintenance";
  static const harvest = "Harvest";
  static const inProgress = 'In progress';
  static const stepTwoNewFarmDescription = 'Description:';
  static const keepText = 'Keep';
  static const enterPassword = 'Enter your password';
}
